CREATE TABLE `rentalApplications` (
	`id` varchar(64) NOT NULL,
	`propertyId` varchar(64),
	`propertyAddress` text,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`dateOfBirth` varchar(20) NOT NULL,
	`ssn` varchar(20),
	`currentAddress` text NOT NULL,
	`currentCity` varchar(100) NOT NULL,
	`currentState` varchar(2) NOT NULL,
	`currentZip` varchar(10) NOT NULL,
	`currentLengthOfResidence` varchar(50),
	`currentLandlordName` varchar(255),
	`currentLandlordPhone` varchar(20),
	`currentMonthlyRent` varchar(20),
	`reasonForLeaving` text,
	`employmentStatus` enum('employed','self_employed','unemployed','retired','student') NOT NULL,
	`employerName` varchar(255),
	`employerPhone` varchar(20),
	`employerAddress` text,
	`jobTitle` varchar(255),
	`monthsEmployed` int,
	`monthlyIncome` varchar(20),
	`additionalIncome` varchar(20),
	`additionalIncomeSource` text,
	`references` json,
	`additionalOccupants` json,
	`hasPets` boolean DEFAULT false,
	`petDetails` text,
	`hasEviction` boolean DEFAULT false,
	`evictionDetails` text,
	`hasCriminalHistory` boolean DEFAULT false,
	`criminalDetails` text,
	`hasBankruptcy` boolean DEFAULT false,
	`bankruptcyDetails` text,
	`hasVoucher` boolean DEFAULT false,
	`voucherType` enum('section8_hcv','vash','other'),
	`phaName` varchar(255),
	`phaPhone` varchar(20),
	`phaEmail` varchar(320),
	`voucherNumber` varchar(100),
	`voucherAmount` varchar(20),
	`voucherBedrooms` varchar(10),
	`voucherExpirationDate` varchar(20),
	`applicationFee` decimal(8,2) DEFAULT '75.00',
	`paymentStatus` enum('pending','paid','refunded') DEFAULT 'pending',
	`stripePaymentIntentId` varchar(255),
	`stripeClientSecret` varchar(512),
	`status` enum('incomplete','submitted','under_review','approved','denied','withdrawn') DEFAULT 'incomplete',
	`reviewNotes` text,
	`reviewedBy` varchar(64),
	`reviewedAt` timestamp,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `rentalApplications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `rentalApplications` ADD CONSTRAINT `rentalApplications_propertyId_properties_id_fk` FOREIGN KEY (`propertyId`) REFERENCES `properties`(`id`) ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `rentalApplications` ADD CONSTRAINT `rentalApplications_reviewedBy_users_id_fk` FOREIGN KEY (`reviewedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;